grupo51_proyecto_homepage:
    pattern:  /
    defaults: { _controller: Grupo51ProyectoBundle:Default:index }
#HomePage de nuestro proyecto
grupo51_proyecto_homepage:
    pattern:  /home
    defaults: { _controller: Grupo51ProyectoBundle:User:home }