grupo51_proyecto_homepage:
    pattern:  /
    defaults: { _controller: Grupo51ProyectoBundle:Default:index }

grupo51_proyecto_home:
    pattern:  /home
    defaults: { _controller: Grupo51ProyectoBundle:User:home }